# Header
menu:
  Home: /
  Archives: /archives
  about:/about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

excerpt_link: Read All #替换为中文

plugins:

twitter: #右边栏要显示twitter展示的话，需要在此设置
  username: moxie198
  show_replies: false
  tweet_count: 5

addthis: #SNS分享，身在天朝，当然用“百度分享”，暂时默认，后面会介绍
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true
    

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

fancybox: true #图片效果，默认

# Miscellaneous
google_analytics:
rss:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
